name: "apihut"
mode: "debug"
#mode: "release"
port: 8080

mysql:
  host: "127.0.0.1"
  port: 33061
  user: "root"
  password: "123456"
  dbname: "apihut"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100